apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-tax-labels
  namespace: ai-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app-tax-labels #This should be same label
  template:
    metadata:
      labels:
        app: ml-app-tax-labels #This should be same label
    spec:
      containers:
      - name: ml-app-tax-labels
        image: pdesaidocker/ml-classification-tax-labels:v1
        ports:
        - containerPort: 5000 #port defined in image dockerfile
       