apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-tax-labels
  namespace: ai-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app-tax-labels #This should be same label
  template:
    metadata:
      labels:
        app: ml-app-tax-labels #This should be same label
    spec:
      containers:
      - name: ml-app-tax-labels
        image: pdesaidocker/ml-classification-tax-labels:{{imageTag}}
        resources:
          requests:
            memory: "128Mi"   # Minimum memory for the container to function
            cpu: "25m"       # Minimum CPU for the container to function
          limits:
            memory: "256Mi"   # Maximum memory that can be used
            cpu: "50m"       # Maximum CPU that can be used
        ports:
        - containerPort: 5000 #port defined in image dockerfile
       
